name: Run unit tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: [self-hosted, linux, x64]

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Restore'
        run: dotnet restore

      - name: 'Build'
        run: dotnet build

      - name: 'Test'
        working-directory: tests
        run: dotnet test
